# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker-hub'
      repository: 'sophiakaterinis/devops-pipeline'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

  - task: KubernetesManifest@1
    inputs:
      action: 'deploy'
      connectionType: 'azureResourceManager'
      azureSubscriptionConnection: 'Sophia Katerinis DevOps(bdfe0c7e-bc86-4ebf-86fa-4d99c0057e2b)'
      azureResourceGroup: 'networking-resource-group'
      kubernetesCluster: 'terraform-aks-cluster'
      manifests: 'application-manifest.yaml'